name: template

# will run on weekdays at 08:00 (Kiev TZ) / 03:00 EST
# on:
#   schedule:
#     - cron: '0 5 * * 1-5'
on:
  push:
    branches:
      - template

# variables https://github.com/alexzavg/playwright_automation_showcase/settings/variables/actions
env:
  ENV_NAME: ${{vars.STAGE_ENV_NAME}}
  TEST_SUITE: ${{vars.TEMPLATE}}
  
jobs:
  template:
    runs-on: ubuntu-latest

    steps:
    - name: List all environment variables
      run: |
        echo "Environment variables:"
        env | sort

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm install
        npm install -g ts-node
        npx playwright install chrome

    - name: 'Create .env file'
      run: |
        touch .env.stage
        echo "${{secrets.CONFIG_STAGE}}" > .env.stage

    - name: Run Integration tests
      run: |
        xvfb-run npm run $TEST_SUITE
